Address Carrick's review.
tlswg/external-psk-design-team pull request #56
Opened 2020-09-15 15:50 UTC by jhoyla

Closes #44, #45, and #47.

2020-09-15 15:53 UTC, jhoyla commented
@cbartle891 does this address your (other) comments?

2020-09-15 21:34 UTC, cbartle891 commented
I think this adds really helpful context to what would otherwise be confusing on its own, thanks.

2020-09-17 12:10 UTC, chris-wood requested changes

2020-09-17 12:10 UTC, chris-wood commented on draft-ietf-tls-external-psk-guidance.md
> +keys, and operating a central server.
"full security" seems too vague. I'd recommend reverting this change, as I don't think it adds much and isn't consistent with the other items in this list. (This bullet item is identifying IoT as a use case, not explaining all the ways in which IoT systems may use PSKs, and why those certain ways are good or bad or whatever.)

2020-09-17 12:10 UTC, chris-wood commented on draft-ietf-tls-external-psk-guidance.md
> +necessary, or to bind a particular action to a particular device.
```suggestion
- Internet of Things (IoT) and devices with limited computational capabilities. Many PSK provisioning examples are possible in this use-case. For example, in a given setting, IoT devices may all share the same PSK and use it to communicate with a central server (one key for n devices), have their own key for communicating with a central server (n keys for n devices), or have pairwise keys for communicating with each other (n^2 keys for n devices). 

The exact provisioning process depends on the system requirements and threat model. Generally, use of 
a single PSK shared between more than one node is not recommended, even if other accommodations 
are made, such as client certificate authentication after PSK-based connection establishment. 
See {{recommendations}}.
```

2020-09-17 12:10 UTC, chris-wood commented on draft-ietf-tls-external-psk-guidance.md
>  with each other using the external PSK. It is important to note that any node of the group can behave
Unrelated to your change, but I'd also suggest rewriting this item:

```suggestion
- Group chats. In this use-case, group participants may be provisioned an external PSK out-of-band for establishing authenticated connections with other members of the group.
```

2020-11-01 01:22 UTC, merged